### ISSUE TITLE
Must find decipher function from script / Something broke when playing the track.

### ISSUE THREAD

**Issue by Mxdi** [lavalink-devs/youtube-source#116]
### Basic Troubleshooting

- [x] I have checked for similar issues (open AND closed), and my issue is not a duplicate. (MANDATORY)
- [x] I have checked for pull requests that may already address my issue. (MANDATORY)
- [x] I am using (and my issue is reproducible on) the latest version of youtube-source.
- [x] My issue is reproducible with IPv6 rotation.

### Version of youtube-source

1.11.5

### The search query/queries, URL(s), playlist ID(s)/URL(s) or video ID(s)/URL(s) that triggered the issue

bn8gP5N8hqM

### Code Example

        const player = await client.kazagumo.createPlayer({
            guildId: message.guild.id,
            textId: message.channel.id,
            voiceId: message.member.voice.channel.id,
            volume: 100
        })

        let results = await client.kazagumo.search(message.content, { requester: message.author });

        (yes there are results...)

        player.queue.add(results.tracks[0]);
        player.play();

### Exception and Stacktrace

2025-03-25T01:06:29.646Z ERROR 13522 --- [Lavalink] [back-1-thread-1] d.l.y.cipher.SignatureCipherManager      : Problematic YouTube player script /s/player/643afba4/player_ias.vflset/en_US/base.js detected (issue detected with script: no decipher function match). Dumped to /tmp/lavaplayer-yt-player-script8581772034308397736.js (Source version: 1.11.5)
2025-03-25T01:06:29.654Z ERROR 13522 --- [Lavalink] [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of bn8gP5N8hqM

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45) ~[lavaplayer-2.2.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:121) ~[lavaplayer-2.2.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339) ~[lavaplayer-2.2.1.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]
Caused by: java.lang.IllegalStateException: Must find decipher function from script.
        at dev.lavalink.youtube.cipher.SignatureCipherManager.extractFromScript(SignatureCipherManager.java:278) ~[youtube-plugin-1.11.5.jar!/:na]
        at dev.lavalink.youtube.cipher.SignatureCipherManager.getCipherScript(SignatureCipherManager.java:219) ~[youtube-plugin-1.11.5.jar!/:na]
        at dev.lavalink.youtube.clients.skeleton.NonMusicClient.loadTrackInfoFromInnertube(NonMusicClient.java:110) ~[youtube-plugin-1.11.5.jar!/:na]
        at dev.lavalink.youtube.clients.skeleton.StreamingNonMusicClient.loadFormats(StreamingNonMusicClient.java:35) ~[youtube-plugin-1.11.5.jar!/:na]
        at dev.lavalink.youtube.track.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:194) ~[youtube-plugin-1.11.5.jar!/:na]
        at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:131) ~[youtube-plugin-1.11.5.jar!/:na]
        at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:79) ~[youtube-plugin-1.11.5.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109) ~[lavaplayer-2.2.1.jar!/:na]
        ... 4 common frames omitted
        Suppressed: dev.lavalink.youtube.ClientInformation:
  yts.version: 1.11.5
  client.identifier: TVHTML5_SIMPLY_EMBEDDED_PLAYER
  client.options: ClientOptions{playback=true, playlistLoading=true, videoLoading=true, searching=true}

### What is your client configuration?

      - TVHTML5EMBEDDED       - MWEB       - WEB       - WEBEMBEDDED

**Comment by IoIxD** [comment]
Duplicate of #114

**Comment by Mxdi** [comment]
> Duplicate of [#114](https://github.com/lavalink-devs/youtube-source/issues/114)

Good observation

**Comment by IoIxD** [comment]
I point it out because this was resolved as a result of that issue.

You can get the snapshot build that fixes this issue [here](https://maven.lavalink.dev/#/snapshots/dev/lavalink/youtube/youtube-plugin/008faf9f7a39c3f98d24fc1d5c98a9dc960a377c)

**Comment by NotViper** [comment]
same issues here...
i have an issue with my lavalink too

**Comment by IttoSanzzo** [comment]
the same as. It was working on version 1.11.4 until a few minutes ago, and out of nowhere, it suddenly broke. I updated to 1.11.5, and it's still broken, rotating the available clients didn't work either

**Comment by dazzypark** [comment]
try

```yaml
    - dependency: "dev.lavalink.youtube:youtube-plugin:294d3c50380705fe8de585aabd960f612f79d083"
      snapshot: true # Set to true if you want to use a snapshot version.
```

**Comment by NotViper** [comment]
Try [https://maven.lavalink.dev/#/snapshots/dev/lavalink/youtube/youtube-plugin/294d3c50380705fe8de585aabd960f612f79d083](this)
